language: python
python: "2.7"
sudo: required
addons:
  apt:
    packages:
      - python-pip
os:
  - linux
  - osx
install:
  - pip install ansible
  - ansible --version
  - printf '\n%s\n%s\n' '[privilege_escalation]' 'become = True' >> ansible.cfg
script:
  - ansible-playbook tests/test.yml -i tests/inventory
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: false
