language: generic
sudo: required
os:
  - linux
  - osx
install:
  - test "$(which apt-get)" && apt-get update && apt-get install ansible
  - test "$(which brew)" && brew update && brew install ansible
  - ansible --version
  - printf '\n%s\n%s\n' '[privilege_escalation]' 'become = True' >> ansible.cfg
script:
  - ansible-playbook tests/test.yml -i tests/inventory
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: false
