language: generic
sudo: required
addons:
  apt:
    packages:
      - python-pip
os:
  - linux
  - osx
install:
  - if [ "$(uname)" = "Darwin" ]; then brew update && brew install ansible; fi
  - if [ "$(uname)" = "Linux" ]; then pip install ansible; fi
  - ansible --version
  - test "$(uname)" = "Darwin" || printf '\n%s\n%s\n' '[privilege_escalation]' 'become = True' >> ansible.cfg
script:
  - ansible-playbook tests/test.yml -i tests/inventory
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: false
