language: generic
sudo: required
addons:
  apt:
    packages:
      - ansible
os:
  - linux
  - osx
install:
  - test "$(uname)" = "Darwin" && brew update && brew install ansible
  - ansible --version
  - test "$(uname)" = "Darwin" || printf '\n%s\n%s\n' '[privilege_escalation]' 'become = True' >> ansible.cfg
script:
  - ansible-playbook tests/test.yml -i tests/inventory
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: false
