- file: path="{{ item }}" state=absent
  with_fileglob:
    - "{{ eclipse_home }}/plugins/org.eclipse.jpt.*"
    - "{{ eclipse_home }}/features/org.eclipse.jpt.*"
    - "{{ eclipse_home }}/plugins/*jgit*"
    - "{{ eclipse_home }}/features/*jgit*"
    - "{{ eclipse_home }}/plugins/*egit*"
    - "{{ eclipse_home }}/features/*egit*"
